/* eslint-disable max-lines */
export interface IEmojiItem {
    char: string;
    keywords: string;
}

export interface IEmojiCategory {
    id: string;
    label: string;
    icon: string;
}

export const emojiCategories: IEmojiCategory[] = [
    { id: 'all', label: 'All', icon: '🔣' },
    { id: 'smileys', label: 'Smileys & Emotions', icon: '😀' },
    { id: 'gestures', label: 'Hand Gestures', icon: '✋' },
    { id: 'hearts', label: 'Hearts', icon: '❤️' },
    { id: 'animals', label: 'Animals', icon: '🐶' },
    { id: 'nature', label: 'Nature & Weather', icon: '🌿' },
    { id: 'food', label: 'Food & Drink', icon: '🍎' },
    { id: 'activities', label: 'Activities & Sports', icon: '⚽' },
    { id: 'travel', label: 'Travel & Places', icon: '🚗' },
    { id: 'objects', label: 'Objects', icon: '💻' },
    { id: 'symbols', label: 'Symbols', icon: '✅' }
];

export const emojiData: Record<string, IEmojiItem[]> = {
    smileys: [
        { char: '😀', keywords: 'grinning face happy smile' },
        { char: '😃', keywords: 'grinning face big eyes happy' },
        { char: '😄', keywords: 'grinning face smiling eyes happy' },
        { char: '😁', keywords: 'beaming face grin happy' },
        { char: '😆', keywords: 'grinning squinting laughing happy' },
        { char: '😅', keywords: 'grinning sweat nervous laugh' },
        { char: '🤣', keywords: 'rolling floor laughing rofl' },
        { char: '😂', keywords: 'tears of joy laughing lol cry' },
        { char: '🙂', keywords: 'slightly smiling face' },
        { char: '🙃', keywords: 'upside down face silly' },
        { char: '😉', keywords: 'winking face wink' },
        { char: '😊', keywords: 'smiling face blushing happy' },
        { char: '😇', keywords: 'smiling halo angel innocent' },
        { char: '🥰', keywords: 'smiling hearts love adore' },
        { char: '😍', keywords: 'heart eyes love crush' },
        { char: '🤩', keywords: 'star struck excited amazed' },
        { char: '😘', keywords: 'blowing kiss love' },
        { char: '😗', keywords: 'kissing face' },
        { char: '😚', keywords: 'kissing closed eyes' },
        { char: '😙', keywords: 'kissing smiling eyes' },
        { char: '🥲', keywords: 'smiling tear happy sad' },
        { char: '😋', keywords: 'face savoring food yum tasty' },
        { char: '😛', keywords: 'face tongue out playful' },
        { char: '😜', keywords: 'winking tongue out silly' },
        { char: '🤪', keywords: 'zany face goofy crazy' },
        { char: '😝', keywords: 'squinting tongue out' },
        { char: '🤑', keywords: 'money mouth rich dollar' },
        { char: '🤗', keywords: 'hugging face hug' },
        { char: '🤭', keywords: 'hand over mouth giggle oops' },
        { char: '🤫', keywords: 'shushing quiet silence secret' },
        { char: '🤔', keywords: 'thinking face hmm consider' },
        { char: '🙄', keywords: 'rolling eyes annoyed' },
        { char: '😬', keywords: 'grimacing awkward nervous' },
        { char: '😴', keywords: 'sleeping face sleep zzz' },
        { char: '🤤', keywords: 'drooling face hungry' },
        { char: '😷', keywords: 'face mask sick medical' },
        { char: '🤒', keywords: 'face thermometer sick ill' },
        { char: '🤕', keywords: 'face bandage hurt injured' },
        { char: '🤧', keywords: 'sneezing face sick tissue' },
        { char: '🥵', keywords: 'hot face sweating heat' },
        { char: '🥶', keywords: 'cold face freezing' },
        { char: '🥴', keywords: 'woozy face dizzy drunk' },
        { char: '😵', keywords: 'dizzy face knocked out' },
        { char: '🤯', keywords: 'exploding head mind blown shocked' },
        { char: '😎', keywords: 'smiling sunglasses cool' },
        { char: '🤓', keywords: 'nerd face geek glasses' },
        { char: '🧐', keywords: 'face monocle inspect curious' },
        { char: '🥳', keywords: 'partying face celebration birthday' },
        { char: '😕', keywords: 'confused face unsure' },
        { char: '😟', keywords: 'worried face concerned' },
        { char: '🙁', keywords: 'slightly frowning sad' },
        { char: '☹️', keywords: 'frowning face sad' },
        { char: '😮', keywords: 'face open mouth surprised wow' },
        { char: '😯', keywords: 'hushed face surprised' },
        { char: '😲', keywords: 'astonished face shocked' },
        { char: '😳', keywords: 'flushed face embarrassed' },
        { char: '🥺', keywords: 'pleading face puppy eyes beg' },
        { char: '😢', keywords: 'crying face sad tear' },
        { char: '😭', keywords: 'loudly crying sobbing sad' },
        { char: '😱', keywords: 'screaming fear scared shocked' },
        { char: '😖', keywords: 'confounded face frustrated' },
        { char: '😞', keywords: 'disappointed face sad' },
        { char: '😩', keywords: 'weary face tired' },
        { char: '😫', keywords: 'tired face exhausted' },
        { char: '🥱', keywords: 'yawning face bored sleepy' },
        { char: '😤', keywords: 'face steam nose frustrated triumph' },
        { char: '😡', keywords: 'pouting face angry mad rage' },
        { char: '😠', keywords: 'angry face mad' },
        { char: '🤬', keywords: 'cursing face swearing angry' },
        { char: '😈', keywords: 'smiling imp devil horns' },
        { char: '👿', keywords: 'angry imp devil' },
        { char: '💀', keywords: 'skull death dead' },
        { char: '💩', keywords: 'pile of poo poop funny' },
        { char: '🤡', keywords: 'clown face' },
        { char: '👻', keywords: 'ghost boo halloween' },
        { char: '👽', keywords: 'alien ufo extraterrestrial' },
        { char: '🤖', keywords: 'robot face bot' },
        { char: '😺', keywords: 'grinning cat happy' },
        { char: '😻', keywords: 'cat heart eyes love' },
        { char: '🙀', keywords: 'weary cat shocked' }
    ],
    gestures: [
        { char: '👋', keywords: 'waving hand hello bye wave' },
        { char: '🤚', keywords: 'raised back of hand' },
        { char: '🖐', keywords: 'hand fingers splayed' },
        { char: '✋', keywords: 'raised hand stop high five' },
        { char: '🖖', keywords: 'vulcan salute spock' },
        { char: '👌', keywords: 'ok hand perfect' },
        { char: '🤌', keywords: 'pinched fingers italian' },
        { char: '🤏', keywords: 'pinching hand small tiny' },
        { char: '✌️', keywords: 'victory peace fingers' },
        { char: '🤞', keywords: 'crossed fingers luck hope' },
        { char: '🤟', keywords: 'love you gesture' },
        { char: '🤘', keywords: 'sign of horns rock' },
        { char: '🤙', keywords: 'call me hand shaka' },
        { char: '👈', keywords: 'backhand index pointing left' },
        { char: '👉', keywords: 'backhand index pointing right' },
        { char: '👆', keywords: 'backhand index pointing up' },
        { char: '🖕', keywords: 'middle finger rude' },
        { char: '👇', keywords: 'backhand index pointing down' },
        { char: '☝️', keywords: 'index pointing up' },
        { char: '👍', keywords: 'thumbs up like approve yes' },
        { char: '👎', keywords: 'thumbs down dislike no' },
        { char: '✊', keywords: 'raised fist power' },
        { char: '👊', keywords: 'oncoming fist punch bump' },
        { char: '🤛', keywords: 'left facing fist' },
        { char: '🤜', keywords: 'right facing fist' },
        { char: '👏', keywords: 'clapping hands applause' },
        { char: '🙌', keywords: 'raising hands celebration praise' },
        { char: '🤝', keywords: 'handshake deal agreement' },
        { char: '🙏', keywords: 'folded hands please thanks pray' },
        { char: '✍️', keywords: 'writing hand sign' },
        { char: '💅', keywords: 'nail polish manicure' },
        { char: '🤳', keywords: 'selfie phone' },
        { char: '💪', keywords: 'flexed biceps strong muscle' },
        { char: '🦾', keywords: 'mechanical arm prosthetic' },
        { char: '🦿', keywords: 'mechanical leg prosthetic' },
        { char: '🦶', keywords: 'foot' },
        { char: '🦵', keywords: 'leg' },
        { char: '👂', keywords: 'ear listen' },
        { char: '👃', keywords: 'nose smell' },
        { char: '👀', keywords: 'eyes looking see' },
        { char: '👁', keywords: 'eye see' },
        { char: '👅', keywords: 'tongue taste' },
        { char: '👄', keywords: 'mouth lips' },
        { char: '🧠', keywords: 'brain mind smart' }
    ],
    hearts: [
        { char: '❤️', keywords: 'red heart love' },
        { char: '🧡', keywords: 'orange heart love' },
        { char: '💛', keywords: 'yellow heart love' },
        { char: '💚', keywords: 'green heart love' },
        { char: '💙', keywords: 'blue heart love' },
        { char: '💜', keywords: 'purple heart love' },
        { char: '🖤', keywords: 'black heart' },
        { char: '🤍', keywords: 'white heart' },
        { char: '🤎', keywords: 'brown heart' },
        { char: '💔', keywords: 'broken heart heartbreak' },
        { char: '❤️‍🔥', keywords: 'heart on fire burning love' },
        { char: '❤️‍🩹', keywords: 'mending heart healing' },
        { char: '💕', keywords: 'two hearts love' },
        { char: '💞', keywords: 'revolving hearts love' },
        { char: '💓', keywords: 'beating heart love' },
        { char: '💗', keywords: 'growing heart love' },
        { char: '💖', keywords: 'sparkling heart love' },
        { char: '💘', keywords: 'heart with arrow cupid love' },
        { char: '💝', keywords: 'heart with ribbon gift love' },
        { char: '💟', keywords: 'heart decoration' },
        { char: '❣️', keywords: 'heart exclamation love' },
        { char: '💌', keywords: 'love letter envelope heart' },
        { char: '💋', keywords: 'kiss mark lips lipstick' }
    ],
    animals: [
        { char: '🐶', keywords: 'dog face puppy' },
        { char: '🐱', keywords: 'cat face kitten' },
        { char: '🐭', keywords: 'mouse face' },
        { char: '🐹', keywords: 'hamster face' },
        { char: '🐰', keywords: 'rabbit face bunny' },
        { char: '🦊', keywords: 'fox face' },
        { char: '🐻', keywords: 'bear face' },
        { char: '🐼', keywords: 'panda face' },
        { char: '🐨', keywords: 'koala' },
        { char: '🐯', keywords: 'tiger face' },
        { char: '🦁', keywords: 'lion face' },
        { char: '🐮', keywords: 'cow face' },
        { char: '🐷', keywords: 'pig face' },
        { char: '🐸', keywords: 'frog face' },
        { char: '🐵', keywords: 'monkey face' },
        { char: '🐔', keywords: 'chicken hen' },
        { char: '🐧', keywords: 'penguin' },
        { char: '🐦', keywords: 'bird' },
        { char: '🐤', keywords: 'baby chick' },
        { char: '🦆', keywords: 'duck' },
        { char: '🦅', keywords: 'eagle' },
        { char: '🦉', keywords: 'owl' },
        { char: '🦇', keywords: 'bat' },
        { char: '🐺', keywords: 'wolf face' },
        { char: '🐗', keywords: 'boar pig' },
        { char: '🐴', keywords: 'horse face' },
        { char: '🦄', keywords: 'unicorn magical' },
        { char: '🐝', keywords: 'honeybee bee' },
        { char: '🐛', keywords: 'bug caterpillar' },
        { char: '🦋', keywords: 'butterfly' },
        { char: '🐌', keywords: 'snail slow' },
        { char: '🐞', keywords: 'lady beetle ladybug' },
        { char: '🐜', keywords: 'ant' },
        { char: '🦗', keywords: 'cricket grasshopper' },
        { char: '🕷', keywords: 'spider' },
        { char: '🦂', keywords: 'scorpion' },
        { char: '🐢', keywords: 'turtle tortoise' },
        { char: '🐍', keywords: 'snake serpent' },
        { char: '🦎', keywords: 'lizard reptile' },
        { char: '🦖', keywords: 'trex dinosaur' },
        { char: '🐙', keywords: 'octopus' },
        { char: '🦑', keywords: 'squid' },
        { char: '🦐', keywords: 'shrimp prawn' },
        { char: '🦀', keywords: 'crab' },
        { char: '🐠', keywords: 'tropical fish' },
        { char: '🐟', keywords: 'fish' },
        { char: '🐬', keywords: 'dolphin' },
        { char: '🐳', keywords: 'spouting whale' },
        { char: '🐋', keywords: 'whale' },
        { char: '🦈', keywords: 'shark' },
        { char: '🐊', keywords: 'crocodile alligator' },
        { char: '🐅', keywords: 'tiger' },
        { char: '🐆', keywords: 'leopard' },
        { char: '🦓', keywords: 'zebra' },
        { char: '🦍', keywords: 'gorilla' },
        { char: '🐘', keywords: 'elephant' },
        { char: '🦏', keywords: 'rhinoceros rhino' },
        { char: '🦛', keywords: 'hippopotamus hippo' },
        { char: '🐪', keywords: 'camel' },
        { char: '🦒', keywords: 'giraffe' },
        { char: '🦘', keywords: 'kangaroo' },
        { char: '🐃', keywords: 'water buffalo' },
        { char: '🐄', keywords: 'cow' },
        { char: '🐎', keywords: 'horse racing' },
        { char: '🐖', keywords: 'pig' },
        { char: '🐏', keywords: 'ram sheep' },
        { char: '🐑', keywords: 'ewe sheep' },
        { char: '🦙', keywords: 'llama alpaca' },
        { char: '🐐', keywords: 'goat' },
        { char: '🦌', keywords: 'deer' },
        { char: '🐕', keywords: 'dog' },
        { char: '🐈', keywords: 'cat' },
        { char: '🐓', keywords: 'rooster' },
        { char: '🦃', keywords: 'turkey' },
        { char: '🦚', keywords: 'peacock' },
        { char: '🦜', keywords: 'parrot' },
        { char: '🦢', keywords: 'swan' },
        { char: '🕊', keywords: 'dove peace bird' },
        { char: '🦝', keywords: 'raccoon' },
        { char: '🦡', keywords: 'badger' },
        { char: '🐿', keywords: 'chipmunk squirrel' },
        { char: '🦔', keywords: 'hedgehog' }
    ],
    nature: [
        { char: '🌱', keywords: 'seedling plant sprout' },
        { char: '🌲', keywords: 'evergreen tree pine' },
        { char: '🌳', keywords: 'deciduous tree' },
        { char: '🌴', keywords: 'palm tree tropical' },
        { char: '🌵', keywords: 'cactus desert' },
        { char: '🌾', keywords: 'sheaf of rice grain' },
        { char: '🌿', keywords: 'herb leaves plant' },
        { char: '☘️', keywords: 'shamrock clover' },
        { char: '🍀', keywords: 'four leaf clover luck' },
        { char: '🍁', keywords: 'maple leaf autumn fall' },
        { char: '🍂', keywords: 'fallen leaves autumn' },
        { char: '🍃', keywords: 'leaf fluttering wind' },
        { char: '🌷', keywords: 'tulip flower' },
        { char: '🌹', keywords: 'rose flower love' },
        { char: '🥀', keywords: 'wilted flower' },
        { char: '🌺', keywords: 'hibiscus flower' },
        { char: '🌸', keywords: 'cherry blossom flower sakura' },
        { char: '🌼', keywords: 'blossom flower daisy' },
        { char: '🌻', keywords: 'sunflower' },
        { char: '🌞', keywords: 'sun with face sunny' },
        { char: '🌝', keywords: 'full moon face' },
        { char: '🌛', keywords: 'first quarter moon face' },
        { char: '🌙', keywords: 'crescent moon night' },
        { char: '⭐', keywords: 'star' },
        { char: '🌟', keywords: 'glowing star sparkle' },
        { char: '✨', keywords: 'sparkles shine glitter' },
        { char: '⚡', keywords: 'high voltage lightning bolt' },
        { char: '☄️', keywords: 'comet' },
        { char: '🔥', keywords: 'fire flame hot lit' },
        { char: '🌈', keywords: 'rainbow' },
        { char: '☀️', keywords: 'sun sunny clear' },
        { char: '⛅', keywords: 'sun behind cloud partly cloudy' },
        { char: '☁️', keywords: 'cloud cloudy' },
        { char: '🌧', keywords: 'cloud rain rainy' },
        { char: '⛈', keywords: 'thunderstorm storm' },
        { char: '🌩', keywords: 'cloud lightning thunder' },
        { char: '🌨', keywords: 'cloud snow snowy' },
        { char: '❄️', keywords: 'snowflake cold winter' },
        { char: '☃️', keywords: 'snowman winter' },
        { char: '⛄', keywords: 'snowman without snow' },
        { char: '🌬', keywords: 'wind face blowing' },
        { char: '💨', keywords: 'dashing wind fast' },
        { char: '💧', keywords: 'droplet water drop' },
        { char: '💦', keywords: 'sweat droplets splash' },
        { char: '🌊', keywords: 'water wave ocean sea' },
        { char: '🌋', keywords: 'volcano eruption' },
        { char: '🏔', keywords: 'snow capped mountain' },
        { char: '⛰', keywords: 'mountain' },
        { char: '🌍', keywords: 'globe earth europe africa world' },
        { char: '🌎', keywords: 'globe earth americas world' },
        { char: '🌏', keywords: 'globe earth asia australia world' }
    ],
    food: [
        { char: '🍎', keywords: 'red apple fruit' },
        { char: '🍊', keywords: 'tangerine orange fruit' },
        { char: '🍋', keywords: 'lemon fruit' },
        { char: '🍌', keywords: 'banana fruit' },
        { char: '🍉', keywords: 'watermelon fruit' },
        { char: '🍇', keywords: 'grapes fruit' },
        { char: '🍓', keywords: 'strawberry fruit' },
        { char: '🫐', keywords: 'blueberries fruit' },
        { char: '🍈', keywords: 'melon fruit' },
        { char: '🍒', keywords: 'cherries fruit' },
        { char: '🍑', keywords: 'peach fruit' },
        { char: '🥭', keywords: 'mango fruit' },
        { char: '🍍', keywords: 'pineapple fruit' },
        { char: '🥥', keywords: 'coconut' },
        { char: '🥝', keywords: 'kiwi fruit' },
        { char: '🍅', keywords: 'tomato vegetable' },
        { char: '🍆', keywords: 'eggplant aubergine vegetable' },
        { char: '🥑', keywords: 'avocado' },
        { char: '🥦', keywords: 'broccoli vegetable' },
        { char: '🥬', keywords: 'leafy green lettuce vegetable' },
        { char: '🥒', keywords: 'cucumber vegetable' },
        { char: '🌶', keywords: 'hot pepper chili spicy' },
        { char: '🌽', keywords: 'corn maize' },
        { char: '🥕', keywords: 'carrot vegetable' },
        { char: '🧄', keywords: 'garlic' },
        { char: '🧅', keywords: 'onion' },
        { char: '🥔', keywords: 'potato' },
        { char: '🍠', keywords: 'roasted sweet potato yam' },
        { char: '🥐', keywords: 'croissant bread' },
        { char: '🥖', keywords: 'baguette bread' },
        { char: '🍞', keywords: 'bread loaf' },
        { char: '🥨', keywords: 'pretzel' },
        { char: '🧀', keywords: 'cheese' },
        { char: '🥚', keywords: 'egg' },
        { char: '🍳', keywords: 'cooking fried egg' },
        { char: '🥞', keywords: 'pancakes breakfast' },
        { char: '🧇', keywords: 'waffle breakfast' },
        { char: '🥓', keywords: 'bacon' },
        { char: '🍔', keywords: 'hamburger burger' },
        { char: '🍟', keywords: 'french fries chips' },
        { char: '🍕', keywords: 'pizza slice' },
        { char: '🌭', keywords: 'hot dog' },
        { char: '🥪', keywords: 'sandwich' },
        { char: '🌮', keywords: 'taco mexican' },
        { char: '🌯', keywords: 'burrito wrap' },
        { char: '🥙', keywords: 'stuffed flatbread kebab' },
        { char: '🍝', keywords: 'spaghetti pasta' },
        { char: '🍜', keywords: 'steaming bowl ramen noodles' },
        { char: '🍲', keywords: 'pot of food stew' },
        { char: '🍛', keywords: 'curry rice' },
        { char: '🍣', keywords: 'sushi' },
        { char: '🍱', keywords: 'bento box' },
        { char: '🍚', keywords: 'cooked rice' },
        { char: '🍙', keywords: 'rice ball onigiri' },
        { char: '🍘', keywords: 'rice cracker' },
        { char: '🍢', keywords: 'oden skewer' },
        { char: '🍡', keywords: 'dango sweet' },
        { char: '🍧', keywords: 'shaved ice dessert' },
        { char: '🍨', keywords: 'ice cream' },
        { char: '🍦', keywords: 'soft ice cream cone' },
        { char: '🥧', keywords: 'pie' },
        { char: '🧁', keywords: 'cupcake' },
        { char: '🍰', keywords: 'shortcake cake slice' },
        { char: '🎂', keywords: 'birthday cake' },
        { char: '🍮', keywords: 'custard pudding flan' },
        { char: '🍭', keywords: 'lollipop candy' },
        { char: '🍬', keywords: 'candy sweet' },
        { char: '🍫', keywords: 'chocolate bar' },
        { char: '🍿', keywords: 'popcorn' },
        { char: '🍩', keywords: 'doughnut donut' },
        { char: '🍪', keywords: 'cookie' },
        { char: '☕', keywords: 'hot beverage coffee tea' },
        { char: '🍵', keywords: 'teacup tea green' },
        { char: '🧃', keywords: 'beverage box juice' },
        { char: '🥤', keywords: 'cup straw soda drink' },
        { char: '🧋', keywords: 'bubble tea boba' },
        { char: '🍺', keywords: 'beer mug' },
        { char: '🍻', keywords: 'clinking beer mugs cheers' },
        { char: '🍷', keywords: 'wine glass' },
        { char: '🍸', keywords: 'cocktail glass martini' },
        { char: '🍹', keywords: 'tropical drink' },
        { char: '🥂', keywords: 'clinking glasses champagne cheers' },
        { char: '🍾', keywords: 'bottle popping champagne celebration' }
    ],
    activities: [
        { char: '⚽', keywords: 'soccer football ball' },
        { char: '🏀', keywords: 'basketball ball' },
        { char: '🏈', keywords: 'american football ball' },
        { char: '⚾', keywords: 'baseball ball' },
        { char: '🥎', keywords: 'softball ball' },
        { char: '🎾', keywords: 'tennis ball' },
        { char: '🏐', keywords: 'volleyball ball' },
        { char: '🏉', keywords: 'rugby football ball' },
        { char: '🥏', keywords: 'flying disc frisbee' },
        { char: '🎱', keywords: 'pool 8 ball billiards' },
        { char: '🏓', keywords: 'ping pong table tennis' },
        { char: '🏸', keywords: 'badminton' },
        { char: '🏒', keywords: 'ice hockey' },
        { char: '🏑', keywords: 'field hockey' },
        { char: '🥍', keywords: 'lacrosse' },
        { char: '🏏', keywords: 'cricket bat ball' },
        { char: '🪃', keywords: 'boomerang' },
        { char: '🥅', keywords: 'goal net' },
        { char: '⛳', keywords: 'flag in hole golf' },
        { char: '🪁', keywords: 'kite' },
        { char: '🏹', keywords: 'bow and arrow archery' },
        { char: '🎣', keywords: 'fishing pole' },
        { char: '🤿', keywords: 'diving mask scuba' },
        { char: '🥊', keywords: 'boxing glove' },
        { char: '🥋', keywords: 'martial arts uniform karate judo' },
        { char: '🎽', keywords: 'running shirt sash' },
        { char: '⛸', keywords: 'ice skate skating' },
        { char: '🥌', keywords: 'curling stone' },
        { char: '🛷', keywords: 'sled sledding' },
        { char: '🎿', keywords: 'skis skiing' },
        { char: '⛷', keywords: 'skier' },
        { char: '🏂', keywords: 'snowboarder' },
        { char: '🏋️', keywords: 'weight lifting gym workout' },
        { char: '🤼', keywords: 'wrestling' },
        { char: '🤸', keywords: 'cartwheel gymnastics' },
        { char: '⛹️', keywords: 'bouncing ball basketball' },
        { char: '🤺', keywords: 'fencing sword' },
        { char: '🤾', keywords: 'handball' },
        { char: '🏌️', keywords: 'golfing golf' },
        { char: '🏇', keywords: 'horse racing jockey' },
        { char: '🧘', keywords: 'lotus yoga meditation' },
        { char: '🏄', keywords: 'surfing surfer' },
        { char: '🏊', keywords: 'swimming swimmer' },
        { char: '🚣', keywords: 'rowing boat' },
        { char: '🚴', keywords: 'cycling biking' },
        { char: '🚵', keywords: 'mountain biking' },
        { char: '🎯', keywords: 'darts bullseye target' },
        { char: '🎳', keywords: 'bowling' },
        { char: '🎮', keywords: 'video game controller gaming' },
        { char: '🕹', keywords: 'joystick arcade' },
        { char: '🎲', keywords: 'dice game' },
        { char: '♟', keywords: 'chess pawn' },
        { char: '🧩', keywords: 'puzzle piece jigsaw' },
        { char: '🎰', keywords: 'slot machine gambling' },
        { char: '🎨', keywords: 'artist palette painting art' },
        { char: '🎭', keywords: 'performing arts theater drama' },
        { char: '🎬', keywords: 'clapper board movie film' },
        { char: '🎤', keywords: 'microphone singing karaoke' },
        { char: '🎧', keywords: 'headphone music listen' },
        { char: '🎼', keywords: 'musical score sheet music' },
        { char: '🎹', keywords: 'musical keyboard piano' },
        { char: '🥁', keywords: 'drum' },
        { char: '🎷', keywords: 'saxophone sax' },
        { char: '🎺', keywords: 'trumpet' },
        { char: '🎸', keywords: 'guitar' },
        { char: '🎻', keywords: 'violin' },
        { char: '🪕', keywords: 'banjo' }
    ],
    travel: [
        { char: '🚗', keywords: 'car automobile' },
        { char: '🚕', keywords: 'taxi cab' },
        { char: '🚙', keywords: 'suv recreational vehicle' },
        { char: '🚌', keywords: 'bus' },
        { char: '🚎', keywords: 'trolleybus' },
        { char: '🏎', keywords: 'racing car race' },
        { char: '🚓', keywords: 'police car' },
        { char: '🚑', keywords: 'ambulance' },
        { char: '🚒', keywords: 'fire engine truck' },
        { char: '🚐', keywords: 'minibus van' },
        { char: '🛻', keywords: 'pickup truck' },
        { char: '🚚', keywords: 'delivery truck' },
        { char: '🚛', keywords: 'articulated lorry truck' },
        { char: '🚜', keywords: 'tractor farm' },
        { char: '🏍', keywords: 'motorcycle bike' },
        { char: '🛵', keywords: 'motor scooter' },
        { char: '🚲', keywords: 'bicycle bike cycle' },
        { char: '🛴', keywords: 'kick scooter' },
        { char: '🛹', keywords: 'skateboard' },
        { char: '✈️', keywords: 'airplane plane flight' },
        { char: '🚁', keywords: 'helicopter' },
        { char: '🚂', keywords: 'locomotive train steam' },
        { char: '🚆', keywords: 'train' },
        { char: '🚇', keywords: 'metro subway underground' },
        { char: '🚊', keywords: 'tram' },
        { char: '🚉', keywords: 'station train' },
        { char: '🚄', keywords: 'high speed train bullet' },
        { char: '🚅', keywords: 'bullet train shinkansen' },
        { char: '🚈', keywords: 'light rail' },
        { char: '🚝', keywords: 'monorail' },
        { char: '🚞', keywords: 'mountain railway' },
        { char: '🚋', keywords: 'tram car' },
        { char: '🚍', keywords: 'oncoming bus' },
        { char: '🛺', keywords: 'auto rickshaw tuk tuk' },
        { char: '', keywords: 'roller skate' },
        { char: '⛵', keywords: 'sailboat sailing' },
        { char: '🚤', keywords: 'speedboat' },
        { char: '🛥', keywords: 'motor boat' },
        { char: '🚢', keywords: 'ship cruise' },
        { char: '⚓', keywords: 'anchor' },
        { char: '🛶', keywords: 'canoe kayak' },
        { char: '🚀', keywords: 'rocket launch space' },
        { char: '🛸', keywords: 'flying saucer ufo' },
        { char: '🚏', keywords: 'bus stop' },
        { char: '🗺', keywords: 'world map travel' },
        { char: '🧭', keywords: 'compass direction' },
        { char: '🏕', keywords: 'camping tent' },
        { char: '🏖', keywords: 'beach umbrella' },
        { char: '🏝', keywords: 'desert island tropical' },
        { char: '🏜', keywords: 'desert' },
        { char: '🌃', keywords: 'night with stars city' },
        { char: '🌆', keywords: 'cityscape dusk' },
        { char: '🌇', keywords: 'sunset buildings' },
        { char: '🌉', keywords: 'bridge night' },
        { char: '🗽', keywords: 'statue of liberty new york' },
        { char: '🗼', keywords: 'tokyo tower' },
        { char: '🏰', keywords: 'castle' },
        { char: '🏯', keywords: 'japanese castle' },
        { char: '🎡', keywords: 'ferris wheel' },
        { char: '🎢', keywords: 'roller coaster' },
        { char: '🎠', keywords: 'carousel horse merry go round' },
        { char: '⛲', keywords: 'fountain' },
        { char: '🗿', keywords: 'moai statue easter island' }
    ],
    objects: [
        { char: '⌚', keywords: 'watch time wrist' },
        { char: '📱', keywords: 'mobile phone smartphone' },
        { char: '💻', keywords: 'laptop computer' },
        { char: '⌨️', keywords: 'keyboard' },
        { char: '🖥', keywords: 'desktop computer' },
        { char: '🖨', keywords: 'printer' },
        { char: '🖱', keywords: 'computer mouse' },
        { char: '🖲', keywords: 'trackball' },
        { char: '🕹', keywords: 'joystick game' },
        { char: '💾', keywords: 'floppy disk save' },
        { char: '💿', keywords: 'optical disc cd' },
        { char: '📀', keywords: 'dvd disc' },
        { char: '📼', keywords: 'videocassette vhs tape' },
        { char: '📷', keywords: 'camera photo' },
        { char: '📸', keywords: 'camera with flash photo' },
        { char: '📹', keywords: 'video camera' },
        { char: '🎥', keywords: 'movie camera film' },
        { char: '📞', keywords: 'telephone receiver phone' },
        { char: '☎️', keywords: 'telephone phone' },
        { char: '📟', keywords: 'pager' },
        { char: '📠', keywords: 'fax machine' },
        { char: '📺', keywords: 'television tv' },
        { char: '📻', keywords: 'radio' },
        { char: '🎙', keywords: 'studio microphone mic' },
        { char: '🎚', keywords: 'level slider' },
        { char: '🎛', keywords: 'control knobs' },
        { char: '🧭', keywords: 'compass' },
        { char: '⏱', keywords: 'stopwatch timer' },
        { char: '⏰', keywords: 'alarm clock' },
        { char: '⌛', keywords: 'hourglass done time' },
        { char: '⏳', keywords: 'hourglass flowing time' },
        { char: '🔋', keywords: 'battery charge power' },
        { char: '🔌', keywords: 'electric plug power' },
        { char: '💡', keywords: 'light bulb idea' },
        { char: '🔦', keywords: 'flashlight torch' },
        { char: '🕯', keywords: 'candle' },
        { char: '🧯', keywords: 'fire extinguisher' },
        { char: '🛢', keywords: 'oil drum barrel' },
        { char: '💸', keywords: 'money with wings cash spend' },
        { char: '💵', keywords: 'dollar banknote money' },
        { char: '💴', keywords: 'yen banknote money' },
        { char: '💶', keywords: 'euro banknote money' },
        { char: '💷', keywords: 'pound banknote money' },
        { char: '💰', keywords: 'money bag cash' },
        { char: '💳', keywords: 'credit card payment' },
        { char: '💎', keywords: 'gem stone diamond jewel' },
        { char: '⚖️', keywords: 'balance scale justice law' },
        { char: '🔧', keywords: 'wrench tool fix' },
        { char: '🔨', keywords: 'hammer tool' },
        { char: '🛠', keywords: 'hammer and wrench tools' },
        { char: '⚙️', keywords: 'gear settings cog' },
        { char: '🔩', keywords: 'nut and bolt' },
        { char: '🧰', keywords: 'toolbox tools' },
        { char: '🧲', keywords: 'magnet' },
        { char: '🔫', keywords: 'water pistol gun toy' },
        { char: '💣', keywords: 'bomb explosive' },
        { char: '🔪', keywords: 'kitchen knife cut' },
        { char: '🗡', keywords: 'dagger knife' },
        { char: '🛡', keywords: 'shield protection' },
        { char: '🔬', keywords: 'microscope science' },
        { char: '🔭', keywords: 'telescope astronomy' },
        { char: '🧪', keywords: 'test tube chemistry lab' },
        { char: '🧬', keywords: 'dna science genetics' },
        { char: '💊', keywords: 'pill medicine drug' },
        { char: '💉', keywords: 'syringe injection vaccine' },
        { char: '🩹', keywords: 'adhesive bandage band aid' },
        { char: '🌡', keywords: 'thermometer temperature' },
        { char: '🧴', keywords: 'lotion bottle' },
        { char: '🧷', keywords: 'safety pin' },
        { char: '🧹', keywords: 'broom sweep clean' },
        { char: '🧺', keywords: 'basket laundry' },
        { char: '🧻', keywords: 'roll of paper toilet' },
        { char: '🚽', keywords: 'toilet' },
        { char: '🚿', keywords: 'shower' },
        { char: '🛁', keywords: 'bathtub bath' },
        { char: '🔑', keywords: 'key lock' },
        { char: '🗝', keywords: 'old key' },
        { char: '🔒', keywords: 'locked closed secure' },
        { char: '🔓', keywords: 'unlocked open' },
        { char: '🔐', keywords: 'locked with key secure' },
        { char: '🔔', keywords: 'bell notification ring' },
        { char: '📌', keywords: 'pushpin pin' },
        { char: '📎', keywords: 'paperclip' },
        { char: '✂️', keywords: 'scissors cut' },
        { char: '🖊', keywords: 'pen write' },
        { char: '✏️', keywords: 'pencil write' },
        { char: '📝', keywords: 'memo note writing' },
        { char: '📖', keywords: 'open book reading' },
        { char: '📚', keywords: 'books library' },
        { char: '📦', keywords: 'package box shipping' },
        { char: '✉️', keywords: 'envelope email mail' },
        { char: '📧', keywords: 'email mail message' },
        { char: '📅', keywords: 'calendar date' },
        { char: '📆', keywords: 'tear off calendar' },
        { char: '📍', keywords: 'round pushpin location pin' },
        { char: '🔍', keywords: 'magnifying glass search left' },
        { char: '🔎', keywords: 'magnifying glass search right' }
    ],
    symbols: [
        { char: '❤️', keywords: 'red heart love' },
        { char: '💛', keywords: 'yellow heart love' },
        { char: '💚', keywords: 'green heart love' },
        { char: '💙', keywords: 'blue heart love' },
        { char: '💜', keywords: 'purple heart love' },
        { char: '🖤', keywords: 'black heart' },
        { char: '🤍', keywords: 'white heart' },
        { char: '💯', keywords: 'hundred points perfect score' },
        { char: '💢', keywords: 'anger symbol angry' },
        { char: '💬', keywords: 'speech balloon bubble' },
        { char: '👁️‍🗨️', keywords: 'eye in speech bubble' },
        { char: '🗨', keywords: 'left speech bubble' },
        { char: '🗯', keywords: 'right anger bubble' },
        { char: '💭', keywords: 'thought balloon bubble' },
        { char: '💤', keywords: 'zzz sleep sleeping' },
        { char: '✅', keywords: 'check mark tick done yes' },
        { char: '⭕', keywords: 'hollow red circle o' },
        { char: '❌', keywords: 'cross mark x no' },
        { char: '⚠️', keywords: 'warning caution' },
        { char: '❗', keywords: 'exclamation mark' },
        { char: '❓', keywords: 'question mark' },
        { char: '❔', keywords: 'white question mark' },
        { char: '❕', keywords: 'white exclamation mark' },
        { char: '‼️', keywords: 'double exclamation mark' },
        { char: '⁉️', keywords: 'exclamation question mark' },
        { char: '〽️', keywords: 'part alternation mark' },
        { char: '⚜️', keywords: 'fleur de lis' },
        { char: '🔱', keywords: 'trident emblem' },
        { char: '⭐', keywords: 'star favorite' },
        { char: '🌟', keywords: 'glowing star' },
        { char: '⚡', keywords: 'lightning bolt high voltage' },
        { char: '🔆', keywords: 'bright button brightness' },
        { char: '🔅', keywords: 'dim button brightness low' },
        { char: '♻️', keywords: 'recycling symbol recycle' },
        { char: '⚛️', keywords: 'atom symbol science' },
        { char: '🔰', keywords: 'beginner japanese symbol' },
        { char: '✳️', keywords: 'eight spoked asterisk' },
        { char: '✴️', keywords: 'eight pointed star' },
        { char: '❇️', keywords: 'sparkle' },
        { char: '©️', keywords: 'copyright' },
        { char: '®️', keywords: 'registered trademark' },
        { char: '™️', keywords: 'trade mark trademark' },
        { char: '🔟', keywords: 'keycap ten 10' },
        { char: '🔢', keywords: 'input numbers 1234' },
        { char: '#️⃣', keywords: 'keycap hash pound' },
        { char: '*️⃣', keywords: 'keycap asterisk star' },
        { char: '➕', keywords: 'plus add' },
        { char: '➖', keywords: 'minus subtract' },
        { char: '➗', keywords: 'divide division' },
        { char: '✖️', keywords: 'multiply multiplication x' },
        { char: '🟰', keywords: 'heavy equals sign' },
        { char: '♾️', keywords: 'infinity forever' },
        { char: '💲', keywords: 'heavy dollar sign money' },
        { char: '➰', keywords: 'curly loop' },
        { char: '➿', keywords: 'double curly loop' },
        { char: '🔚', keywords: 'end arrow' },
        { char: '🔙', keywords: 'back arrow' },
        { char: '🔛', keywords: 'on arrow' },
        { char: '🔝', keywords: 'top arrow up' },
        { char: '🔜', keywords: 'soon arrow' },
        { char: '⬆️', keywords: 'up arrow' },
        { char: '⬇️', keywords: 'down arrow' },
        { char: '⬅️', keywords: 'left arrow' },
        { char: '➡️', keywords: 'right arrow' },
        { char: '↗️', keywords: 'up right arrow' },
        { char: '↘️', keywords: 'down right arrow' },
        { char: '↩️', keywords: 'right arrow curving left return' },
        { char: '🔃', keywords: 'clockwise vertical arrows refresh' },
        { char: '🔄', keywords: 'counterclockwise arrows refresh sync' },
        { char: '▶️', keywords: 'play button' },
        { char: '⏸️', keywords: 'pause button' },
        { char: '⏹️', keywords: 'stop button' },
        { char: '⏺️', keywords: 'record button' },
        { char: '⏭️', keywords: 'next track skip forward' },
        { char: '⏮️', keywords: 'previous track skip back' },
        { char: '🔀', keywords: 'shuffle tracks random' },
        { char: '🔁', keywords: 'repeat loop' },
        { char: '🔂', keywords: 'repeat single' },
        { char: '🔊', keywords: 'speaker high volume loud' },
        { char: '🔇', keywords: 'muted speaker mute' },
        { char: '✔️', keywords: 'check mark tick done' },
        { char: '☑️', keywords: 'check box checked' },
        { char: '🟢', keywords: 'green circle' },
        { char: '🔴', keywords: 'red circle' },
        { char: '🟡', keywords: 'yellow circle' },
        { char: '🔵', keywords: 'blue circle' },
        { char: '⚫', keywords: 'black circle' },
        { char: '⚪', keywords: 'white circle' },
        { char: '🟥', keywords: 'red square' },
        { char: '🟩', keywords: 'green square' },
        { char: '🟦', keywords: 'blue square' },
        { char: '🟨', keywords: 'yellow square' }
    ]
};
