name: Publish @tooloogle/tools NPM Package

on:
  workflow_run:
    workflows: ['Build and Test @tooloogle/tools NPM Package']
    branches: [release]
    types:
      - completed

  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm ci
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - run: npm run build
      - run: cd dist
      - name: Publish git npm package
        run: |
          npm install -g @semantic-release/changelog @semantic-release/git semantic-release 
          GITHUB_REF=${{ env.GITHUB_TRIGGER_REF }} semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}