const tools = [
  'age-calculator',
  'direct-to-whatsapp',
  'email-validator',
  'date-format',
  'gold-purity-calculator',
  'url-encoder-decoder',
  'password-generator',
  'temperature-converter',
  'base64-encoder-decoder',
  'text-case-converter',
  'base64-to-image',
  'image-to-base64',
  'hex-rgb',
  'guid-generator',
  'qr-code-generator',
  'bytes-to-string-converter',
  'hex-to-rgba-converter',
  'rgba-color-picker',
  'hex-color-picker',
  'css-gradient-generator',
  'javascript-beautifier',
  'css-beautifier',
  'html-beautifier',
  'json-viewer',
  'csv-to-json-converter',
  'json-to-csv-converter',
  'regex-expression-tester',
  'text-to-speech',
  'qr-code-scanner',
  'heif-to-png-converter',
  'heif-to-jpg-converter',
  'md5-hash-generator',
  'bmi-calculator',
  'xml-to-json-converter',
  'json-to-xml-converter',
  'svg-optimizer',
  'webp-to-jpg-converter',
  'webp-to-png-converter',
  'jpg-to-webp-converter',
  'png-to-webp-converter',
  'email-template-generator',
  'resume-builder',
  'stylish-text-generator',
];

if (typeof window !== 'undefined') {
  window.tools = tools;
}

export default tools;
