name: Build and Test @tooloogle/tools NPM Package

on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm run lint
      - run: npm run css
      - run: npm run test
      - run: npm run build:tools
      - run: npm run build:demo
